Sending sms dev
wiktorwieclaw/Nokia-PK-2021 pull request #7
Opened 2021-04-22 10:42 UTC by Blazej-Zielinski

2021-04-22 14:08 UTC, wiktorwieclaw requested changes
Everything seems fine except the lack of sms encryption. I've made some smaller suggestions that should make the code clearer.  Please don't forget about proper formatting with clang-format.

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/ISmsDb.hpp
> +#include <Messages/PhoneNumber.hpp>
use "" instead of <>

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/ISmsDb.hpp
> +    virtual void addSms(const common::PhoneNumber& receiverPhoneNumber, const std::string& text) = 0;
change addSms to addSentSms
make it take Sms struct as a parameter this may require changes to Sms and/or SmsDb

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/BtsPort.cpp
> +void BtsPort::sendSms(const common::PhoneNumber &receiverPhoneNumber,const std::string& text)
formatting
make it take Sms struct as a parameter, this may require changes to Sms and/or SmsDb

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/BtsPort.cpp
> +    msg.writeText(text);
lack of encryption

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/BtsPort.hpp
> +    void sendSms(const common::PhoneNumber &receiverPhoneNumber,const std::string& text) override;
formatting
make it take Sms struct as a parameter, this may require changes to Sms and/or SmsDb

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/IBtsPort.hpp
> +#include <Messages/PhoneNumber.hpp>
use "" instead of <>

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/IBtsPort.hpp
> +    virtual void sendSms(const common::PhoneNumber &receiverPhoneNumber,const std::string& text) = 0;
formatting
make it take Sms struct as a parameter, this may require changes to Sms and/or SmsDb

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/UserPort.cpp
> +        switch (menu.getCurrentItemIndex().second)
consider using ```auto [first, second] = menu.getCurrentItemIndex()``` and give variables proper names for clarity

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/UserPort.cpp
> +        };
unnecessary ```;```

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/UserPort.cpp
> +    gui.setAcceptCallback([this,&menu]{
formatting

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/UserPort.cpp
> +}
return Sms instead of pair

Get rid of getSmsData(). Pass Sms to handleSendSms() directly in setAcceptCallback's lambda;

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/UserPort.hpp
> +    std::pair<common::PhoneNumber, SmsText> getSmsData() override;
remove (see above)

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/Ports/UserPort.hpp
> +    IUeGui::ISmsComposeMode* mode = nullptr;
remove (see above)

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/SmsDb.cpp
> +
change parameters to Sms

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/SmsDb.hpp
> +    Send
grammar, change Send to Sent

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Tests/Application/SmsDbTestSuite.cpp
> +    const common::PhoneNumber receiverPhoneNumber = common::PhoneNumber{113};
use auto

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Tests/Application/Ports/BtsPortTestSuite.cpp
> +    const common::PhoneNumber receiverPhoneNumber = common::PhoneNumber{113};
auto

2021-04-22 14:08 UTC, wiktorwieclaw commented on UE/Application/SmsDb.hpp
> +    void addSms(const common::PhoneNumber& receiverPhoneNumber,const std::string& text) override;
change parameters to single Sms parameter

2021-04-28 14:25 UTC, filip6464 approved these changes

2021-04-28 14:28 UTC, filip6464 reviewed
I have nothing to add to Wiktor's comments. Including his suggestions everything would be fine.

2021-04-28 23:10 UTC, wiktorwieclaw commented on UE/Application/Ports/BtsPort.cpp
> +    msg.writeText(text);
Not an issue right now. See point 4.3 in specification.

2021-04-28 23:12 UTC, wiktorwieclaw commented
> Everything seems fine except the **lack of sms encryption**. 

I don't think that we are supposed to implement this right now as it is an "advanced feature" and will be discussed at the lectures. See specification 4.3.

2021-05-01 11:38 UTC, filip6464 requested changes
I found one not needed using and one small error with accept callback. The rest is okay.

2021-05-01 11:38 UTC, filip6464 commented on UE/Application/Ports/IUserPort.hpp
> +    using SmsText = std::string;
Is it necessary here?

2021-05-01 11:38 UTC, filip6464 commented on UE/Application/Ports/UserPort.cpp
> +        switch (index)
You forgot to check if isSelected is true

2021-05-01 14:17 UTC, wiktorwieclaw approved these changes

2021-05-01 14:19 UTC, filip6464 approved these changes

2021-05-01 14:21 UTC, merged